language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - echo "Before Install"
  - export NODE_ENV=development

script:
  - npm test

script:
  - node test/fake_json_api.js &
  - mocha test/json/*Spec.js

script:
  - node test/fake_xml_api.js &
  - mocha test/xml/*Spec.js

after_success:
  - echo "DONE and SUCCESS!"
